---
hosts: localhost
connection: local
vars:
  eda_validate_certs: false
  eda_host: aap.kona.services:8445
  eda_username: "{{ eda_username }}"
  eda_password: "{{ eda_passwd }}"

pre_tasks:
  - name: Include vars from controller_configs directory
    ansible.builtin.include_vars:
      dir: ./vars
      ignore_files: [controller_config.yml.template]
      extensions: ["yml"]

roles:
  - {role: infra.eda_configuration.user, when: eda_users is defined}
